# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=true
org.gradle.configuration-cache=false
org.gradle.java.installations.fromEnv=JAVA8,JAVA16,JAVA17,JAVA21,JAVA25

essential.defaults.loom=0
essential.defaults.loom.fabric-loader=net.fabricmc:fabric-loader:0.19.1

version=1.13
loom.ignoreDependencyLoomVersionValidation=true
